/*
 * @Author: tuojinxin
 * @Date: 2023-05-11 17:43:49
 * @LastEditTime: 2023-05-12 17:57:33
 * @LastEditors: tuojinxin
 * @Description: 
 */
###
GET http://localhost:3000 HTTP/1.1

###
GET http://localhost:3000/cats/test1 HTTP/1.1

###
GET http://localhost:3000/cats/test2 HTTP/1.1

###
GET http://localhost:3000/cats/test3 HTTP/1.1

###
GET http://localhost:3000/cats/test4 HTTP/1.1

###
GET http://localhost:3000/cats/test5 HTTP/1.1

###
GET http://localhost:3000/cats/test6 HTTP/1.1

###
GET http://localhost:3000/cats/test7 HTTP/1.1